CREATE TABLE TRANSACTION_DATA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_KEY VARCHAR(255) UNIQUE, -- Changed column name to DATA_KEY
    `VALUE` VARCHAR(255)
);

CREATE TABLE TRANSACTION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    `TIMESTAMP` TIMESTAMP,
    TYPE VARCHAR(255),
    ACTOR VARCHAR(255),
    TRANSACTION_DATA_ID INT,
    FOREIGN KEY (TRANSACTION_DATA_ID) REFERENCES TRANSACTION_DATA(ID)
);
